### ISSUE TITLE
SeatAndEat : Make Footer Responsive

### ISSUE THREAD

**Issue by Rupam-Matabber** [DSCKGEC/SeatAndEat#10]
- Make the footer responsive for all devices

**Comment by iamatifmoin** [comment]
I can easily resolve this issue by enhancing some styling. 
Please assign me this.

**Comment by Rupam-Matabber** [comment]
Hey @iamatifmoin , Assigned to you. Best of luck.

**Comment by Suman373** [comment]
In adding the footer, the 2nd point was making footer responsive. So , my issue 16 PR will resolve it anyway @Rupam-Matabber

**Comment by iamatifmoin** [comment]
@Rupam-Matabber I have completed the assigned task. The PR is linked above.
