### ISSUE TITLE
SeatAndEat : Add Favicon To All Pages

### ISSUE THREAD

**Issue by Rupam-Matabber** [DSCKGEC/SeatAndEat#12]
- Add favicon to all pages
- Favicon is already present in the respective folder. Don't add any new favicon

**Comment by Suman373** [comment]
I want to work on this issue @Rupam-Matabber

**Comment by sudip-101** [comment]
Assigned.

**Comment by SWITCHin2** [comment]
Can I also give it a try simultaneously?
