### ISSUE TITLE
SeatAndEat : Change Styles Of About Us Page

### ISSUE THREAD

**Issue by Rajarshi12321** [DSCKGEC/SeatAndEat#15]
- Make about us section responsive

**Comment by iamatifmoin** [comment]
I want to work on this issue.

**Comment by iamatifmoin** [comment]
Are you referring to the 'About Page' or the 'About Us Section'?

**Comment by Rajarshi12321** [comment]
It is referred to the about page

**Comment by iamatifmoin** [comment]
I want to work on this. Can you assign me this issue?

**Comment by Rupam-Matabber** [comment]
Assigned @iamatifmoin
