### ISSUE TITLE
SeatAndEat :  Add Footer To All Pages

### ISSUE THREAD

**Issue by Rajarshi12321** [DSCKGEC/SeatAndEat#16]
- Add Footer to every page, which you would find in the landing page.
- Make it responsive.

**Comment by Suman373** [comment]
What would the footer look like? Can you help me understand.

**Comment by Rajarshi12321** [comment]
The footer is on the landing page (index.html). You have to add that to other pages too. If you want you can make enhancements to make it look better.

**Comment by Suman373** [comment]
> The footer is on the landing page (index.html). You have to add that to other pages too. If you want you can make enhancements to make it look better.

I would like to work on this

**Comment by Rajarshi12321** [comment]
Cool.
You may checkout the  [KSOC website](https://dscksoc.herokuapp.com/) to register yourself to take part in it and learn about the important dates.
Follow [GDSC KGEC linked page](https://www.linkedin.com/company/dsckgec/mycompany/) to learn about the future updates and events.

**Comment by Suman373** [comment]
> Cool. You may checkout the [KSOC website](https://dscksoc.herokuapp.com/) to register yourself to take part in it and learn about the important dates. Follow [GDSC KGEC linked page](https://www.linkedin.com/company/dsckgec/mycompany/) to learn about the future updates and events.

I have registered already. I want to clarify something. I have to add the footer which is in home page to : about,menu and contact us .
These are the changes I need to make?

**Comment by Suman373** [comment]
> Cool. You may checkout the [KSOC website](https://dscksoc.herokuapp.com/) to register yourself to take part in it and learn about the important dates. Follow [GDSC KGEC linked page](https://www.linkedin.com/company/dsckgec/mycompany/) to learn about the future updates and events.

How to get assigned ?

**Comment by Suman373** [comment]
Assign me this issue , I wanna work on it

**Comment by sudip-101** [comment]
Hey @Suman373, I have assigned you this. All the best.
