### ISSUE TITLE
SeatAndEat : Change The Carousel Item Style in Menu Page

### ISSUE THREAD

**Issue by Rupam-Matabber** [DSCKGEC/SeatAndEat#17]
![image](https://user-images.githubusercontent.com/78860897/180836527-3d926fdb-8a82-4fd9-b185-cfae15a1ad92.png)

- Change the styling of the heading, paragraph, and button as shown above.
- Maintain the accent color for the button
- Remember don't change the alignment from center to left
- Add a custom and minimal hover effect to the Learn more button. use the accent color for the hover color.

**Comment by ahmedbilal-2711** [comment]
Please assign this to me

**Comment by soumalya20010** [comment]
Hello @Rupam-Matabber  I would like to work on this issue

**Comment by Rupam-Matabber** [comment]
Assigned to you @soumalya20010

**Comment by vaibhavi-roy** [comment]
Hello @Rajarshi12321 I would like to work on this issue

**Comment by Rupam-Matabber** [comment]
Updates @soumalya20010 ?

**Comment by soumalya20010** [comment]
@Rupam-Matabber done

**Comment by Rupam-Matabber** [comment]
@soumalya20010 You had to change the items on the menu page but you have changed the home page items.

![image](https://user-images.githubusercontent.com/78860897/183260305-86437930-cd59-4f7b-a2fb-9619da5e7111.png)
Change the items on the carousel. The image which is linked to the issue is for your reference. 
Read the instruction carefully and make the changes. Then you can make a new PR.

**Comment by soumalya20010** [comment]
@Rupam-Matabber 
I have made changes to the menu page plz review it thanks.....
