### ISSUE TITLE
SeatAndEat : Add Food Cards To The Menu Page

### ISSUE THREAD

**Issue by Rupam-Matabber** [DSCKGEC/SeatAndEat#18]
![image](https://user-images.githubusercontent.com/78860897/180838189-88f01c3b-2677-4b82-acd8-554bef071695.png)

- Add food cards to the menu page. It should look like the above design. 
- Maintain the accent color when making the cards.
- The background should be dark like the other pages.

**Comment by Rishi1003** [comment]
Hello @Rupam-Matabber I have completed the registration process, I have tried out something similar in the past while learning HTML and CSS so I would like to work on this issue

**Comment by sudip-101** [comment]
Hey @Rishi1003, Assigned. Best of luck.

**Comment by AirSayy** [comment]
Hi @sudip-101  , Ill like to contribute to this project, i have a good basic knowledge of css however im learning how to contribute using github . whats the registration process?
