### ISSUE TITLE
SeatAndEat : Correct grammatical errors throughout the website.

### ISSUE THREAD

**Issue by iamatifmoin** [DSCKGEC/SeatAndEat#29]
**Description of what needs to be done**
All grammatical and punctuation errors in the entire website need to be corrected.

**Why does this need to be done?**
1. This needs to be done to reduce the number of words on the page and provide a better user experience.
2. Pages with better language are usually ranked higher on the internet. (SEO)

**Comment by Rupam-Matabber** [comment]
This issue is against the norms of KSoC.

**Comment by iamatifmoin** [comment]
Okay. But it will make the website look much better. @Rupam-Matabber

**Comment by Rupam-Matabber** [comment]
We will let you know if we open this issue. But currently, it is against the guidelines of the KSoC.

**Comment by iamatifmoin** [comment]
@Rupam-Matabber Okay!
