### ISSUE TITLE
SeatAndEat : Make The Navbar Responsive

### ISSUE THREAD

**Issue by Rupam-Matabber** [DSCKGEC/SeatAndEat#6]
- Make the navbar responsive
- Create a hamburger menu for the navbar dropdown
- Include only the nav list items for the dropdown ( Don't include the SeatAndEat Logo )
- Add a small animation to the hamburger menu icon when clicked

**Comment by JoydevDafadar** [comment]
I want to ba a part of this issue..

**Comment by Rupam-Matabber** [comment]
Assigned to you @JoydevDafadar

**Comment by SWITCHin2** [comment]
Can I work on it simultaneously?

**Comment by Rupam-Matabber** [comment]
Congrats @JoydevDafadar your PR is merged.
