### ISSUE TITLE
SeatAndEat : Make The Popular Dish Section Responsive

### ISSUE THREAD

**Issue by Rupam-Matabber** [DSCKGEC/SeatAndEat#8]
- Make the popular dish section responsive
- Also few changes to be done in the styling :
      * Make all the dish images card the same size
      * Make equal padding and same alignment to the cards

**Comment by iamatifmoin** [comment]
I can resolve this issue as well. Please assign me this @Rupam-Matabber

**Comment by Rupam-Matabber** [comment]
Assigned @iamatifmoin

**Comment by iamatifmoin** [comment]
@Rupam-Matabber I have completed the assigned task. The PR is linked above.

**Comment by iamatifmoin** [comment]
The first image of the dish is slightly smaller compared to the other images. 

I could not fix it. 

But, I think it can be fixed by someone else after you merge this PR.
