### ISSUE TITLE
SeatAndEat : Make Food Categories Section Responsive

### ISSUE THREAD

**Issue by Rupam-Matabber** [DSCKGEC/SeatAndEat#9]
- Make the food categories section responsive for all devices

**Comment by susobhandas07** [comment]
are we using bootstrap or own made media query?

**Comment by Rupam-Matabber** [comment]
@susobhandas07 you have to use your own made media query.

**Comment by susobhandas07** [comment]
Ok, I think css grid should work, assign it to me

**Comment by Rupam-Matabber** [comment]
Assigned to you @susobhandas07. Best of luck

**Comment by Rupam-Matabber** [comment]
Updates @susobhandas07 ?

**Comment by susobhandas07** [comment]
I have fixed the issue, yet to merge to main

**Comment by susobhandas07** [comment]
PR sent
